import type { Metadata } from 'next';
import Link from 'next/link';
import { notFound } from 'next/navigation';
import { loadAllNews, getNewsBySlug, getRelatedNews } from '@/lib/news/loader';
import { brand } from '@/lib/brand';
import { Breadcrumb } from '@/components/Breadcrumb';
import { JsonLd, articleSchema, breadcrumbSchema } from '@/components/Schema';

export function generateStaticParams() {
  return loadAllNews().map((p) => ({ slug: p.id }));
}

export async function generateMetadata({ params }: { params: Promise<{ slug: string }> }): Promise<Metadata> {
  const { slug } = await params;
  const post = getNewsBySlug(slug);
  if (!post) return { title: 'Brief not found' };
  return {
    title: post.title,
    description: post.excerpt,
    alternates: { canonical: `/news/${post.id}/` },
    openGraph: {
      title: post.title,
      description: post.excerpt,
      url: `${brand.url}/news/${post.id}/`,
      type: 'article',
      publishedTime: post.date,
    },
  };
}

const CATEGORY_LABEL: Record<string, string> = {
  'interest-rates': 'Interest rates',
  tax: 'Tax',
  super: 'Super',
  wages: 'Wages',
  inflation: 'Inflation',
  property: 'Property',
  markets: 'Markets',
  policy: 'Policy',
  general: 'General',
};

const RELATED_LABELS: Record<string, string> = {
  mortgage: 'Mortgage calculator',
  'mortgage-calculator': 'Mortgage calculator',
  'loan-payoff-calculator': 'Loan payoff calculator',
  hecs: 'HECS-HELP calculator',
  'hecs-calculator': 'HECS-HELP calculator',
  'salary-sacrifice-calculator': 'Salary sacrifice calculator',
  'casual-pay-calculator': 'Casual pay calculator',
  'guides/australian-income-tax': 'Guide: Australian income tax',
  'guides/hecs-repayment': 'Guide: HECS repayment',
  'guides/superannuation': 'Guide: Superannuation',
  'guides/medicare-levy-surcharge': 'Guide: Medicare levy surcharge',
  'guides/stage-3-tax-cuts': 'Guide: Stage 3 tax cuts',
  'guides/salary-sacrifice': 'Guide: Salary sacrifice',
};

export default async function NewsPostPage({ params }: { params: Promise<{ slug: string }> }) {
  const { slug } = await params;
  const post = getNewsBySlug(slug);
  if (!post) notFound();
  const related = getRelatedNews(post, 3);
  const published = new Date(post.date).toLocaleDateString('en-AU', {
    weekday: 'long',
    day: 'numeric',
    month: 'long',
    year: 'numeric',
  });

  return (
    <>
      <Breadcrumb
        items={[
          { name: 'Home', href: '/' },
          { name: 'Money Briefs', href: '/news/' },
          { name: post.title },
        ]}
      />

      <article className="mt-12">
        {/* Header */}
        <header className="max-w-3xl">
          <div className="flex flex-wrap items-center gap-3">
            <span className="kicker">{CATEGORY_LABEL[post.category] || 'Money brief'}</span>
            <span className="font-mono text-[11px] uppercase tracking-[0.2em] text-ink-500">
              {published}
            </span>
          </div>
          <h1 className="h-display mt-4 text-ink-800">
            {post.title}
          </h1>
          <p className="mt-6 text-base text-ink-600 sm:text-lg">
            {post.excerpt}
          </p>
          <p className="mt-6 text-sm text-ink-600">
            Originally published by{' '}
            <a
              href={post.sourceUrl}
              target="_blank"
              rel="noopener noreferrer"
              className="text-ink-800 underline decoration-1 underline-offset-4 hover:text-ledger-500"
            >
              {post.source}
            </a>
            {post.autoGenerated && (
              <>
                {' '}· Summarised and re-explained by the SalaryCalc editorial bot.
                Auto-generated on {published}.
              </>
            )}
          </p>
        </header>

        <hr className="rule-line my-12" />

        {/* Body — paragraph-by-paragraph */}
        <div className="max-w-3xl space-y-5 text-base text-ink-700 sm:text-lg">
          {post.body.split(/\n\n+/).map((para, i) => (
            <p key={i} className={i === 0 ? 'drop-cap text-ink-700' : ''}>
              {para}
            </p>
          ))}
        </div>

        {/* What it means */}
        <section className="section">
          <p className="section-index">§ What this means for you</p>
          <h2 className="h-section mt-4 text-ink-800">The practical bit.</h2>
          <ul className="mt-8 space-y-5">
            {post.whatItMeans.map((point, i) => {
              const [head, ...rest] = point.split(':');
              const isSplit = rest.length > 0;
              return (
                <li key={i} className="rule-line flex gap-4 border-t border-ink-400 pt-5">
                  <span className="font-mono text-[11px] uppercase tracking-[0.2em] text-ledger-500">
                    {String(i + 1).padStart(2, '0')}
                  </span>
                  <div className="flex-1 text-base text-ink-700 sm:text-lg">
                    {isSplit ? (
                      <>
                        <strong className="font-semibold text-ink-800">{head}:</strong>{' '}
                        {rest.join(':').trim()}
                      </>
                    ) : (
                      point
                    )}
                  </div>
                </li>
              );
            })}
          </ul>
        </section>

        {/* Related calculators */}
        {post.relatedSlugs && post.relatedSlugs.length > 0 && (
          <section className="section">
            <p className="section-index">§ Run the numbers</p>
            <h2 className="h-section mt-4 text-ink-800">Worked examples and calculators.</h2>
            <ul className="mt-8 space-y-0">
              {post.relatedSlugs.map((slug) => (
                <li key={slug} className="rule-line border-t border-ink-400">
                  <Link
                    href={`/${slug}/`}
                    className="trust-row flex items-baseline justify-between gap-4"
                  >
                    <span className="text-lg font-semibold text-ink-800 sm:text-xl">
                      {RELATED_LABELS[slug] || slug}
                    </span>
                    <span className="font-mono text-[11px] uppercase tracking-[0.2em] text-ink-500">
                      Open <span aria-hidden>→</span>
                    </span>
                  </Link>
                </li>
              ))}
            </ul>
          </section>
        )}

        {/* Related briefs */}
        {related.length > 0 && (
          <section className="section">
            <p className="section-index">§ Related briefs</p>
            <h2 className="h-section mt-4 text-ink-800">More on the same topic.</h2>
            <ul className="mt-8 space-y-0">
              {related.map((r) => (
                <li key={r.id} className="rule-line border-t border-ink-400">
                  <Link
                    href={`/news/${r.id}/`}
                    className="block py-6 transition hover:opacity-80"
                  >
                    <p className="font-mono text-[11px] uppercase tracking-[0.2em] text-ink-500">
                      {new Date(r.date).toLocaleDateString('en-AU', { day: '2-digit', month: 'short', year: 'numeric' })} · {r.source}
                    </p>
                    <p className="mt-2 text-lg font-semibold text-ink-800 sm:text-xl">
                      {r.title}
                    </p>
                    <p className="mt-2 max-w-3xl text-sm text-ink-600 sm:text-base">
                      {r.excerpt}
                    </p>
                  </Link>
                </li>
              ))}
            </ul>
          </section>
        )}

        {/* Source & disclaimer */}
        <section className="section">
          <p className="section-index">§ Where this came from</p>
          <h2 className="h-section mt-4 text-ink-800">Source and method.</h2>
          <div className="mt-6 max-w-3xl text-sm text-ink-600 sm:text-base">
            <p>
              This brief is a plain-English summary of news published by{' '}
              <a
                href={post.sourceUrl}
                target="_blank"
                rel="noopener noreferrer"
                className="text-ink-800 underline decoration-1 underline-offset-4 hover:text-ledger-500"
              >
                {post.source}
              </a>
              . We do not speak for the original publisher. Always cross-check the
              primary source — especially for tax, super, and legal decisions — and
              consider talking to a registered tax agent or financial adviser before
              acting on anything in this brief.
            </p>
            <p className="mt-4">
              SalaryCalc publishes Money Briefs for general information. It is not
              financial or tax advice. See our{' '}
              <Link href="/disclaimer/" className="underline decoration-1 underline-offset-4 hover:text-ledger-500">disclaimer</Link>.
            </p>
          </div>
        </section>
      </article>

      <JsonLd
        data={[
          breadcrumbSchema([
            { name: 'Home', url: brand.url },
            { name: 'Money Briefs', url: `${brand.url}/news/` },
            { name: post.title, url: `${brand.url}/news/${post.id}/` },
          ]),
          articleSchema({
            headline: post.title,
            description: post.excerpt,
            datePublished: post.date,
            url: `${brand.url}/news/${post.id}/`,
          }),
        ]}
      />
    </>
  );
}
