export type NewsCategory =
  | 'interest-rates'
  | 'tax'
  | 'super'
  | 'wages'
  | 'inflation'
  | 'property'
  | 'markets'
  | 'policy'
  | 'general';

export type NewsSource =
  | 'Reserve Bank of Australia'
  | 'ABC News'
  | 'Sydney Morning Herald'
  | 'The Guardian Australia'
  | 'Australian Taxation Office'
  | 'Treasury';

export interface NewsPost {
  /** Unique id (date-prefixed kebab slug). */
  id: string;
  /** ISO date the post was published. */
  date: string;
  /** Headline as displayed on the site. */
  title: string;
  /** Short summary shown in listings & meta description (max ~160 chars). */
  excerpt: string;
  /** Source publication name. */
  source: NewsSource;
  /** Original article URL on the source's site. */
  sourceUrl: string;
  /** Category for filtering / colour-coding. */
  category: NewsCategory;
  /** Optional kicker (e.g. "RBA · Media release"). */
  kicker?: string;
  /** Layman explanation body in markdown-style plain text (rendered as paragraphs). */
  body: string;
  /** Short "what this means for you" bullets. */
  whatItMeans: string[];
  /** Optional list of related calculator / guide slugs. */
  relatedSlugs?: string[];
  /** Authoring note (e.g. "Auto-generated from RSS"). */
  autoGenerated?: boolean;
}
