import type { Metadata } from 'next';
import Link from 'next/link';
import { loadAllNews } from '@/lib/news/loader';
import { brand } from '@/lib/brand';
import { Breadcrumb } from '@/components/Breadcrumb';
import { NewsletterForm } from '@/components/NewsletterForm';
import { JsonLd, articleSchema, breadcrumbSchema } from '@/components/Schema';

export const metadata: Metadata = {
  title: 'Money Briefs, Australian financial news, explained',
  description: `Weekly money briefs from ${brand.name}. The week's biggest Australian financial news, interest rates, tax, super, wages, property, explained in plain English. Updated Tuesdays and Fridays.`,
  alternates: { canonical: '/news/' },
  openGraph: {
    title: 'Money Briefs, Australian financial news, explained',
    description: 'Weekly money briefs from SalaryCalc. The biggest Australian financial news, explained in plain English.',
    url: `${brand.url}/news/`,
    type: 'website',
  },
};

const CATEGORY_LABEL: Record<string, string> = {
  'interest-rates': 'Interest rates',
  tax: 'Tax',
  super: 'Super',
  wages: 'Wages',
  inflation: 'Inflation',
  property: 'Property',
  markets: 'Markets',
  policy: 'Policy',
  general: 'General',
};

export default function NewsIndexPage() {
  const posts = loadAllNews();
  const featured = posts[0];
  const rest = posts.slice(1);

  return (
    <>
      <Breadcrumb
        items={[
          { name: 'Home', href: '/' },
          { name: 'Money Briefs', href: '/news/' },
        ]}
      />

      {/* Hero */}
      <section className="mt-12">
        <p className="kicker">Money Briefs · {brand.name}</p>
        <h1 className="h-display mt-3 text-ink-800">
          The week in Australian money, <span className="ledger-highlight">explained in plain English.</span>
        </h1>
        <p className="mt-6 max-w-2xl text-base text-ink-600 sm:text-lg">
          Every Tuesday and Friday we pull the biggest Australian financial news from
          trusted sources, the RBA, the ATO, the ABS, the ABC, the Sydney Morning Herald,
          The Guardian, and explain what it means for your pay, your mortgage, your
          super, and your taxes. No jargon. No spin. Just the practical bit.
        </p>
        <p className="mt-4 font-mono text-[11px] uppercase tracking-[0.2em] text-ink-600">
          Sources: RBA · ATO · ABC News · SMH · The Guardian Australia
        </p>
      </section>

      {featured && (
        <section className="section">
          <p className="section-index">§ Featured · {new Date(featured.date).toLocaleDateString('en-AU', { day: 'numeric', month: 'long', year: 'numeric' })}</p>
          <Link
            href={`/news/${featured.id}/`}
            className="group mt-4 block"
          >
            <article className="surface-elevated surface-elevated-hover p-6 sm:p-10">
              <div className="flex flex-wrap items-center gap-3">
                <span className="kicker">{featured.kicker || CATEGORY_LABEL[featured.category] || 'News'}</span>
                <span className="font-mono text-[11px] uppercase tracking-[0.2em] text-ink-600">
                  {new Date(featured.date).toLocaleDateString('en-AU', { day: '2-digit', month: 'short', year: 'numeric' })}
                </span>
              </div>
              <h2 className="h-section mt-4 text-ink-800 group-hover:text-ledger-500">
                {featured.title}
              </h2>
              <p className="mt-4 max-w-3xl text-base text-ink-600 sm:text-lg">
                {featured.excerpt}
              </p>
              <p className="mt-6 inline-flex items-center gap-2 font-mono text-[11px] uppercase tracking-[0.2em] text-ledger-500">
                Read the brief <span aria-hidden>→</span>
              </p>
            </article>
          </Link>
        </section>
      )}

      {/* All briefs */}
      {rest.length > 0 && (
        <section className="section">
          <p className="section-index">§ All briefs</p>
          <h2 className="h-section mt-4 text-ink-800">Everything we have covered.</h2>
          <ul className="mt-10 space-y-0">
            {rest.map((post) => (
              <li key={post.id} className="rule-line border-t border-ink-400">
                <Link
                  href={`/news/${post.id}/`}
                  className="block py-8 transition hover:opacity-80"
                >
                  <div className="flex flex-wrap items-center gap-3">
                    <span className="kicker-neutral">{CATEGORY_LABEL[post.category] || 'News'}</span>
                    <span className="font-mono text-[11px] uppercase tracking-[0.2em] text-ink-600">
                      {new Date(post.date).toLocaleDateString('en-AU', { day: '2-digit', month: 'short', year: 'numeric' })}
                    </span>
                    {post.autoGenerated && (
                      <span className="font-mono text-[10px] uppercase tracking-[0.2em] text-ink-600">
                        · auto
                      </span>
                    )}
                  </div>
                  <h3 className="mt-3 text-xl font-semibold text-ink-800 sm:text-2xl">
                    {post.title}
                  </h3>
                  <p className="mt-2 max-w-3xl text-sm text-ink-600 sm:text-base">
                    {post.excerpt}
                  </p>
                  <p className="mt-4 font-mono text-[11px] uppercase tracking-[0.2em] text-ink-600">
                    {post.source} <span className="text-ink-600">·</span> Read brief <span aria-hidden>→</span>
                  </p>
                </Link>
              </li>
            ))}
          </ul>
        </section>
      )}

      {/* Sources & methodology */}
      <section className="section">
        <p className="section-index">§ How this works</p>
        <h2 className="h-section mt-4 text-ink-800">Where the news comes from.</h2>
        <div className="mt-8 grid gap-6 sm:grid-cols-2">
          {[
            {
              src: 'Reserve Bank of Australia',
              what: 'Cash-rate decisions, statements, minutes, and speeches by the RBA Governor.',
              url: 'https://www.rba.gov.au/media-releases/',
            },
            {
              src: 'Australian Taxation Office',
              what: 'ATO media releases on tax administration, compliance, and rule changes.',
              url: 'https://www.ato.gov.au/Media-centre/Media-releases/',
            },
            {
              src: 'ABC News (Business)',
              what: 'Independent, public-broadcaster coverage of the Australian economy and policy.',
              url: 'https://www.abc.net.au/news/business/',
            },
            {
              src: 'Sydney Morning Herald',
              what: 'Major Australian newspaper, business, markets, property, and personal finance.',
              url: 'https://www.smh.com.au/business',
            },
            {
              src: 'The Guardian Australia',
              what: 'Independent reporting on Australian economics, super, wages, and household finances.',
              url: 'https://www.theguardian.com/au/business',
            },
            {
              src: 'Australian Bureau of Statistics',
              what: 'Wage Price Index, CPI, labour force, and other official economic data.',
              url: 'https://www.abs.gov.au/',
            },
          ].map((s) => (
            <div key={s.src} className="rule-line border-t border-ink-400 pt-5">
              <p className="font-mono text-[11px] uppercase tracking-[0.2em] text-ledger-500">Source</p>
              <p className="mt-2 text-lg font-semibold text-ink-800">{s.src}</p>
              <p className="mt-2 text-sm text-ink-600">{s.what}</p>
              <a
                href={s.url}
                target="_blank"
                rel="noopener noreferrer"
                className="mt-3 inline-block font-mono text-[11px] uppercase tracking-[0.2em] text-ink-600 underline decoration-1 underline-offset-4 hover:text-ledger-500"
              >
                Visit ↗
              </a>
            </div>
          ))}
        </div>
        <p className="mt-10 max-w-2xl text-sm text-ink-600">
          We summarise and re-explain news from these sources in our own words. The
          original article is always linked from the top of every brief. SalaryCalc is
          an independent calculator site; we do not speak for any of the listed
          sources and we are not financial advisers. See our{' '}
          <Link href="/disclaimer/" className="underline decoration-1 underline-offset-4 hover:text-ledger-500">disclaimer</Link>.
        </p>
      </section>

      {/* Newsletter — primary conversion on this page */}
      <section className="section">
        <NewsletterForm
          accessKey={process.env.NEXT_PUBLIC_NEWSLETTER_KEY}
          source="news-page"
          heading="Never miss a Money Brief."
          description="Twice a week, free, in your inbox. The biggest Australian financial news, explained in plain English. About 90 seconds to read each."
        />
      </section>

      <JsonLd
        data={[
          breadcrumbSchema([
            { name: 'Home', url: brand.url },
            { name: 'Money Briefs', url: `${brand.url}/news/` },
          ]),
          ...posts.slice(0, 5).map((p) => articleSchema({
            headline: p.title,
            description: p.excerpt,
            datePublished: p.date,
            url: `${brand.url}/news/${p.id}/`,
          })),
        ]}
      />
    </>
  );
}
